name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Install ffmpeg devel
      run: sudo apt-get install libavcodec-dev libavutil-dev
    - name: Install cairo devel
      run: sudo apt-get install libcairo2-dev

    - uses: actions/checkout@v2

    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
